server:
  port: 8081

spring:
  application:
    name: customer-service

  datasource:
    url: jdbc:postgresql://localhost:5432/hoa_mai_customer
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

  flyway:
    locations: classpath:db/migration

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

management:
  endpoints:
    web:
      exposure:
        include: health,info