server:
  port: 8083

spring:
  application:
    name: transaction-service

  datasource:
    url: jdbc:postgresql://localhost:5432/hoa_mai_transaction
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

  flyway:
    locations: classpath:db/migration

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

app:
  rabbitmq:
    exchange: hoamai.exchange

management:
  endpoints:
    web:
      exposure:
        include: health,info
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
